version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "14:38"
      timezone: America/Toronto
    target-branch: "v2.7.x-release"
    # Labels on pull requests for security and version updates
    labels:
      - "npm 001"
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "v3.0.x-release"
    labels:
      - "npm 004"

