version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: "2.7.x-release"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/"
    target-branch: "v3.0.x-release"
    schedule:
      interval: daily
